/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package org.opencps.paymentmgt.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.opencps.paymentmgt.model.PaymentConfig;
import org.opencps.paymentmgt.model.PaymentConfigModel;
import org.opencps.paymentmgt.model.PaymentConfigSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the PaymentConfig service. Represents a row in the &quot;opencps_payment_config&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.opencps.paymentmgt.model.PaymentConfigModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PaymentConfigImpl}.
 * </p>
 *
 * @author trungdk
 * @see PaymentConfigImpl
 * @see org.opencps.paymentmgt.model.PaymentConfig
 * @see org.opencps.paymentmgt.model.PaymentConfigModel
 * @generated
 */
@JSON(strict = true)
public class PaymentConfigModelImpl extends BaseModelImpl<PaymentConfig>
	implements PaymentConfigModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a Payment configuration model instance should use the {@link org.opencps.paymentmgt.model.PaymentConfig} interface instead.
	 */
	public static final String TABLE_NAME = "opencps_payment_config";
	public static final Object[][] TABLE_COLUMNS = {
			{ "paymentConfigId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "govAgencyOrganizationId", Types.BIGINT },
			{ "govAgencyName", Types.VARCHAR },
			{ "govAgencyTaxNo", Types.VARCHAR },
			{ "invoiceTemplateNo", Types.VARCHAR },
			{ "invoiceIssueNo", Types.VARCHAR },
			{ "invoiceLastNo", Types.VARCHAR },
			{ "bankInfo", Types.VARCHAR },
			{ "placeInfo", Types.VARCHAR },
			{ "keypayDomain", Types.VARCHAR },
			{ "keypayVersion", Types.VARCHAR },
			{ "keypayMerchantCode", Types.VARCHAR },
			{ "keypaySecureKey", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table opencps_payment_config (paymentConfigId LONG not null primary key,companyId LONG,groupId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,govAgencyOrganizationId LONG,govAgencyName VARCHAR(75) null,govAgencyTaxNo VARCHAR(75) null,invoiceTemplateNo VARCHAR(75) null,invoiceIssueNo VARCHAR(75) null,invoiceLastNo VARCHAR(7) null,bankInfo VARCHAR(75) null,placeInfo VARCHAR(75) null,keypayDomain VARCHAR(75) null,keypayVersion VARCHAR(75) null,keypayMerchantCode VARCHAR(75) null,keypaySecureKey VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table opencps_payment_config";
	public static final String ORDER_BY_JPQL = " ORDER BY paymentConfig.paymentConfigId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY opencps_payment_config.paymentConfigId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.opencps.paymentmgt.model.PaymentConfig"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.opencps.paymentmgt.model.PaymentConfig"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.opencps.paymentmgt.model.PaymentConfig"),
			true);
	public static long GOVAGENCYORGANIZATIONID_COLUMN_BITMASK = 1L;
	public static long GROUPID_COLUMN_BITMASK = 2L;
	public static long PAYMENTCONFIGID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static PaymentConfig toModel(PaymentConfigSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		PaymentConfig model = new PaymentConfigImpl();

		model.setPaymentConfigId(soapModel.getPaymentConfigId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setGovAgencyOrganizationId(soapModel.getGovAgencyOrganizationId());
		model.setGovAgencyName(soapModel.getGovAgencyName());
		model.setGovAgencyTaxNo(soapModel.getGovAgencyTaxNo());
		model.setInvoiceTemplateNo(soapModel.getInvoiceTemplateNo());
		model.setInvoiceIssueNo(soapModel.getInvoiceIssueNo());
		model.setInvoiceLastNo(soapModel.getInvoiceLastNo());
		model.setBankInfo(soapModel.getBankInfo());
		model.setPlaceInfo(soapModel.getPlaceInfo());
		model.setKeypayDomain(soapModel.getKeypayDomain());
		model.setKeypayVersion(soapModel.getKeypayVersion());
		model.setKeypayMerchantCode(soapModel.getKeypayMerchantCode());
		model.setKeypaySecureKey(soapModel.getKeypaySecureKey());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<PaymentConfig> toModels(PaymentConfigSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<PaymentConfig> models = new ArrayList<PaymentConfig>(soapModels.length);

		for (PaymentConfigSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.opencps.paymentmgt.model.PaymentConfig"));

	public PaymentConfigModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _paymentConfigId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPaymentConfigId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _paymentConfigId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PaymentConfig.class;
	}

	@Override
	public String getModelClassName() {
		return PaymentConfig.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("paymentConfigId", getPaymentConfigId());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());
		attributes.put("userId", getUserId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("govAgencyOrganizationId", getGovAgencyOrganizationId());
		attributes.put("govAgencyName", getGovAgencyName());
		attributes.put("govAgencyTaxNo", getGovAgencyTaxNo());
		attributes.put("invoiceTemplateNo", getInvoiceTemplateNo());
		attributes.put("invoiceIssueNo", getInvoiceIssueNo());
		attributes.put("invoiceLastNo", getInvoiceLastNo());
		attributes.put("bankInfo", getBankInfo());
		attributes.put("placeInfo", getPlaceInfo());
		attributes.put("keypayDomain", getKeypayDomain());
		attributes.put("keypayVersion", getKeypayVersion());
		attributes.put("keypayMerchantCode", getKeypayMerchantCode());
		attributes.put("keypaySecureKey", getKeypaySecureKey());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long paymentConfigId = (Long)attributes.get("paymentConfigId");

		if (paymentConfigId != null) {
			setPaymentConfigId(paymentConfigId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long govAgencyOrganizationId = (Long)attributes.get(
				"govAgencyOrganizationId");

		if (govAgencyOrganizationId != null) {
			setGovAgencyOrganizationId(govAgencyOrganizationId);
		}

		String govAgencyName = (String)attributes.get("govAgencyName");

		if (govAgencyName != null) {
			setGovAgencyName(govAgencyName);
		}

		String govAgencyTaxNo = (String)attributes.get("govAgencyTaxNo");

		if (govAgencyTaxNo != null) {
			setGovAgencyTaxNo(govAgencyTaxNo);
		}

		String invoiceTemplateNo = (String)attributes.get("invoiceTemplateNo");

		if (invoiceTemplateNo != null) {
			setInvoiceTemplateNo(invoiceTemplateNo);
		}

		String invoiceIssueNo = (String)attributes.get("invoiceIssueNo");

		if (invoiceIssueNo != null) {
			setInvoiceIssueNo(invoiceIssueNo);
		}

		String invoiceLastNo = (String)attributes.get("invoiceLastNo");

		if (invoiceLastNo != null) {
			setInvoiceLastNo(invoiceLastNo);
		}

		String bankInfo = (String)attributes.get("bankInfo");

		if (bankInfo != null) {
			setBankInfo(bankInfo);
		}

		String placeInfo = (String)attributes.get("placeInfo");

		if (placeInfo != null) {
			setPlaceInfo(placeInfo);
		}

		String keypayDomain = (String)attributes.get("keypayDomain");

		if (keypayDomain != null) {
			setKeypayDomain(keypayDomain);
		}

		String keypayVersion = (String)attributes.get("keypayVersion");

		if (keypayVersion != null) {
			setKeypayVersion(keypayVersion);
		}

		String keypayMerchantCode = (String)attributes.get("keypayMerchantCode");

		if (keypayMerchantCode != null) {
			setKeypayMerchantCode(keypayMerchantCode);
		}

		String keypaySecureKey = (String)attributes.get("keypaySecureKey");

		if (keypaySecureKey != null) {
			setKeypaySecureKey(keypaySecureKey);
		}
	}

	@JSON
	@Override
	public long getPaymentConfigId() {
		return _paymentConfigId;
	}

	@Override
	public void setPaymentConfigId(long paymentConfigId) {
		_paymentConfigId = paymentConfigId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getGovAgencyOrganizationId() {
		return _govAgencyOrganizationId;
	}

	@Override
	public void setGovAgencyOrganizationId(long govAgencyOrganizationId) {
		_columnBitmask |= GOVAGENCYORGANIZATIONID_COLUMN_BITMASK;

		if (!_setOriginalGovAgencyOrganizationId) {
			_setOriginalGovAgencyOrganizationId = true;

			_originalGovAgencyOrganizationId = _govAgencyOrganizationId;
		}

		_govAgencyOrganizationId = govAgencyOrganizationId;
	}

	public long getOriginalGovAgencyOrganizationId() {
		return _originalGovAgencyOrganizationId;
	}

	@JSON
	@Override
	public String getGovAgencyName() {
		if (_govAgencyName == null) {
			return StringPool.BLANK;
		}
		else {
			return _govAgencyName;
		}
	}

	@Override
	public void setGovAgencyName(String govAgencyName) {
		_govAgencyName = govAgencyName;
	}

	@JSON
	@Override
	public String getGovAgencyTaxNo() {
		if (_govAgencyTaxNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _govAgencyTaxNo;
		}
	}

	@Override
	public void setGovAgencyTaxNo(String govAgencyTaxNo) {
		_govAgencyTaxNo = govAgencyTaxNo;
	}

	@JSON
	@Override
	public String getInvoiceTemplateNo() {
		if (_invoiceTemplateNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _invoiceTemplateNo;
		}
	}

	@Override
	public void setInvoiceTemplateNo(String invoiceTemplateNo) {
		_invoiceTemplateNo = invoiceTemplateNo;
	}

	@JSON
	@Override
	public String getInvoiceIssueNo() {
		if (_invoiceIssueNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _invoiceIssueNo;
		}
	}

	@Override
	public void setInvoiceIssueNo(String invoiceIssueNo) {
		_invoiceIssueNo = invoiceIssueNo;
	}

	@JSON
	@Override
	public String getInvoiceLastNo() {
		if (_invoiceLastNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _invoiceLastNo;
		}
	}

	@Override
	public void setInvoiceLastNo(String invoiceLastNo) {
		_invoiceLastNo = invoiceLastNo;
	}

	@JSON
	@Override
	public String getBankInfo() {
		if (_bankInfo == null) {
			return StringPool.BLANK;
		}
		else {
			return _bankInfo;
		}
	}

	@Override
	public void setBankInfo(String bankInfo) {
		_bankInfo = bankInfo;
	}

	@JSON
	@Override
	public String getPlaceInfo() {
		if (_placeInfo == null) {
			return StringPool.BLANK;
		}
		else {
			return _placeInfo;
		}
	}

	@Override
	public void setPlaceInfo(String placeInfo) {
		_placeInfo = placeInfo;
	}

	@JSON
	@Override
	public String getKeypayDomain() {
		if (_keypayDomain == null) {
			return StringPool.BLANK;
		}
		else {
			return _keypayDomain;
		}
	}

	@Override
	public void setKeypayDomain(String keypayDomain) {
		_keypayDomain = keypayDomain;
	}

	@JSON
	@Override
	public String getKeypayVersion() {
		if (_keypayVersion == null) {
			return StringPool.BLANK;
		}
		else {
			return _keypayVersion;
		}
	}

	@Override
	public void setKeypayVersion(String keypayVersion) {
		_keypayVersion = keypayVersion;
	}

	@JSON
	@Override
	public String getKeypayMerchantCode() {
		if (_keypayMerchantCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _keypayMerchantCode;
		}
	}

	@Override
	public void setKeypayMerchantCode(String keypayMerchantCode) {
		_keypayMerchantCode = keypayMerchantCode;
	}

	@JSON
	@Override
	public String getKeypaySecureKey() {
		if (_keypaySecureKey == null) {
			return StringPool.BLANK;
		}
		else {
			return _keypaySecureKey;
		}
	}

	@Override
	public void setKeypaySecureKey(String keypaySecureKey) {
		_keypaySecureKey = keypaySecureKey;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			PaymentConfig.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PaymentConfig toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (PaymentConfig)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PaymentConfigImpl paymentConfigImpl = new PaymentConfigImpl();

		paymentConfigImpl.setPaymentConfigId(getPaymentConfigId());
		paymentConfigImpl.setCompanyId(getCompanyId());
		paymentConfigImpl.setGroupId(getGroupId());
		paymentConfigImpl.setUserId(getUserId());
		paymentConfigImpl.setCreateDate(getCreateDate());
		paymentConfigImpl.setModifiedDate(getModifiedDate());
		paymentConfigImpl.setGovAgencyOrganizationId(getGovAgencyOrganizationId());
		paymentConfigImpl.setGovAgencyName(getGovAgencyName());
		paymentConfigImpl.setGovAgencyTaxNo(getGovAgencyTaxNo());
		paymentConfigImpl.setInvoiceTemplateNo(getInvoiceTemplateNo());
		paymentConfigImpl.setInvoiceIssueNo(getInvoiceIssueNo());
		paymentConfigImpl.setInvoiceLastNo(getInvoiceLastNo());
		paymentConfigImpl.setBankInfo(getBankInfo());
		paymentConfigImpl.setPlaceInfo(getPlaceInfo());
		paymentConfigImpl.setKeypayDomain(getKeypayDomain());
		paymentConfigImpl.setKeypayVersion(getKeypayVersion());
		paymentConfigImpl.setKeypayMerchantCode(getKeypayMerchantCode());
		paymentConfigImpl.setKeypaySecureKey(getKeypaySecureKey());

		paymentConfigImpl.resetOriginalValues();

		return paymentConfigImpl;
	}

	@Override
	public int compareTo(PaymentConfig paymentConfig) {
		long primaryKey = paymentConfig.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof PaymentConfig)) {
			return false;
		}

		PaymentConfig paymentConfig = (PaymentConfig)obj;

		long primaryKey = paymentConfig.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		PaymentConfigModelImpl paymentConfigModelImpl = this;

		paymentConfigModelImpl._originalGroupId = paymentConfigModelImpl._groupId;

		paymentConfigModelImpl._setOriginalGroupId = false;

		paymentConfigModelImpl._originalGovAgencyOrganizationId = paymentConfigModelImpl._govAgencyOrganizationId;

		paymentConfigModelImpl._setOriginalGovAgencyOrganizationId = false;

		paymentConfigModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<PaymentConfig> toCacheModel() {
		PaymentConfigCacheModel paymentConfigCacheModel = new PaymentConfigCacheModel();

		paymentConfigCacheModel.paymentConfigId = getPaymentConfigId();

		paymentConfigCacheModel.companyId = getCompanyId();

		paymentConfigCacheModel.groupId = getGroupId();

		paymentConfigCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			paymentConfigCacheModel.createDate = createDate.getTime();
		}
		else {
			paymentConfigCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			paymentConfigCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			paymentConfigCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		paymentConfigCacheModel.govAgencyOrganizationId = getGovAgencyOrganizationId();

		paymentConfigCacheModel.govAgencyName = getGovAgencyName();

		String govAgencyName = paymentConfigCacheModel.govAgencyName;

		if ((govAgencyName != null) && (govAgencyName.length() == 0)) {
			paymentConfigCacheModel.govAgencyName = null;
		}

		paymentConfigCacheModel.govAgencyTaxNo = getGovAgencyTaxNo();

		String govAgencyTaxNo = paymentConfigCacheModel.govAgencyTaxNo;

		if ((govAgencyTaxNo != null) && (govAgencyTaxNo.length() == 0)) {
			paymentConfigCacheModel.govAgencyTaxNo = null;
		}

		paymentConfigCacheModel.invoiceTemplateNo = getInvoiceTemplateNo();

		String invoiceTemplateNo = paymentConfigCacheModel.invoiceTemplateNo;

		if ((invoiceTemplateNo != null) && (invoiceTemplateNo.length() == 0)) {
			paymentConfigCacheModel.invoiceTemplateNo = null;
		}

		paymentConfigCacheModel.invoiceIssueNo = getInvoiceIssueNo();

		String invoiceIssueNo = paymentConfigCacheModel.invoiceIssueNo;

		if ((invoiceIssueNo != null) && (invoiceIssueNo.length() == 0)) {
			paymentConfigCacheModel.invoiceIssueNo = null;
		}

		paymentConfigCacheModel.invoiceLastNo = getInvoiceLastNo();

		String invoiceLastNo = paymentConfigCacheModel.invoiceLastNo;

		if ((invoiceLastNo != null) && (invoiceLastNo.length() == 0)) {
			paymentConfigCacheModel.invoiceLastNo = null;
		}

		paymentConfigCacheModel.bankInfo = getBankInfo();

		String bankInfo = paymentConfigCacheModel.bankInfo;

		if ((bankInfo != null) && (bankInfo.length() == 0)) {
			paymentConfigCacheModel.bankInfo = null;
		}

		paymentConfigCacheModel.placeInfo = getPlaceInfo();

		String placeInfo = paymentConfigCacheModel.placeInfo;

		if ((placeInfo != null) && (placeInfo.length() == 0)) {
			paymentConfigCacheModel.placeInfo = null;
		}

		paymentConfigCacheModel.keypayDomain = getKeypayDomain();

		String keypayDomain = paymentConfigCacheModel.keypayDomain;

		if ((keypayDomain != null) && (keypayDomain.length() == 0)) {
			paymentConfigCacheModel.keypayDomain = null;
		}

		paymentConfigCacheModel.keypayVersion = getKeypayVersion();

		String keypayVersion = paymentConfigCacheModel.keypayVersion;

		if ((keypayVersion != null) && (keypayVersion.length() == 0)) {
			paymentConfigCacheModel.keypayVersion = null;
		}

		paymentConfigCacheModel.keypayMerchantCode = getKeypayMerchantCode();

		String keypayMerchantCode = paymentConfigCacheModel.keypayMerchantCode;

		if ((keypayMerchantCode != null) && (keypayMerchantCode.length() == 0)) {
			paymentConfigCacheModel.keypayMerchantCode = null;
		}

		paymentConfigCacheModel.keypaySecureKey = getKeypaySecureKey();

		String keypaySecureKey = paymentConfigCacheModel.keypaySecureKey;

		if ((keypaySecureKey != null) && (keypaySecureKey.length() == 0)) {
			paymentConfigCacheModel.keypaySecureKey = null;
		}

		return paymentConfigCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(37);

		sb.append("{paymentConfigId=");
		sb.append(getPaymentConfigId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", govAgencyOrganizationId=");
		sb.append(getGovAgencyOrganizationId());
		sb.append(", govAgencyName=");
		sb.append(getGovAgencyName());
		sb.append(", govAgencyTaxNo=");
		sb.append(getGovAgencyTaxNo());
		sb.append(", invoiceTemplateNo=");
		sb.append(getInvoiceTemplateNo());
		sb.append(", invoiceIssueNo=");
		sb.append(getInvoiceIssueNo());
		sb.append(", invoiceLastNo=");
		sb.append(getInvoiceLastNo());
		sb.append(", bankInfo=");
		sb.append(getBankInfo());
		sb.append(", placeInfo=");
		sb.append(getPlaceInfo());
		sb.append(", keypayDomain=");
		sb.append(getKeypayDomain());
		sb.append(", keypayVersion=");
		sb.append(getKeypayVersion());
		sb.append(", keypayMerchantCode=");
		sb.append(getKeypayMerchantCode());
		sb.append(", keypaySecureKey=");
		sb.append(getKeypaySecureKey());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(58);

		sb.append("<model><model-name>");
		sb.append("org.opencps.paymentmgt.model.PaymentConfig");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>paymentConfigId</column-name><column-value><![CDATA[");
		sb.append(getPaymentConfigId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>govAgencyOrganizationId</column-name><column-value><![CDATA[");
		sb.append(getGovAgencyOrganizationId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>govAgencyName</column-name><column-value><![CDATA[");
		sb.append(getGovAgencyName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>govAgencyTaxNo</column-name><column-value><![CDATA[");
		sb.append(getGovAgencyTaxNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>invoiceTemplateNo</column-name><column-value><![CDATA[");
		sb.append(getInvoiceTemplateNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>invoiceIssueNo</column-name><column-value><![CDATA[");
		sb.append(getInvoiceIssueNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>invoiceLastNo</column-name><column-value><![CDATA[");
		sb.append(getInvoiceLastNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>bankInfo</column-name><column-value><![CDATA[");
		sb.append(getBankInfo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>placeInfo</column-name><column-value><![CDATA[");
		sb.append(getPlaceInfo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>keypayDomain</column-name><column-value><![CDATA[");
		sb.append(getKeypayDomain());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>keypayVersion</column-name><column-value><![CDATA[");
		sb.append(getKeypayVersion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>keypayMerchantCode</column-name><column-value><![CDATA[");
		sb.append(getKeypayMerchantCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>keypaySecureKey</column-name><column-value><![CDATA[");
		sb.append(getKeypaySecureKey());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = PaymentConfig.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			PaymentConfig.class
		};
	private long _paymentConfigId;
	private long _companyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _userId;
	private String _userUuid;
	private Date _createDate;
	private Date _modifiedDate;
	private long _govAgencyOrganizationId;
	private long _originalGovAgencyOrganizationId;
	private boolean _setOriginalGovAgencyOrganizationId;
	private String _govAgencyName;
	private String _govAgencyTaxNo;
	private String _invoiceTemplateNo;
	private String _invoiceIssueNo;
	private String _invoiceLastNo;
	private String _bankInfo;
	private String _placeInfo;
	private String _keypayDomain;
	private String _keypayVersion;
	private String _keypayMerchantCode;
	private String _keypaySecureKey;
	private long _columnBitmask;
	private PaymentConfig _escapedModel;
}