/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.opencps.servicemgt.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import org.opencps.servicemgt.model.ServiceFileTemplate;
import org.opencps.servicemgt.model.ServiceFileTemplateModel;
import org.opencps.servicemgt.model.ServiceFileTemplateSoap;
import org.opencps.servicemgt.service.persistence.ServiceFileTemplatePK;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ServiceFileTemplate service. Represents a row in the &quot;opencps_dictitem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.opencps.servicemgt.model.ServiceFileTemplateModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ServiceFileTemplateImpl}.
 * </p>
 *
 * @author khoavd
 * @see ServiceFileTemplateImpl
 * @see org.opencps.servicemgt.model.ServiceFileTemplate
 * @see org.opencps.servicemgt.model.ServiceFileTemplateModel
 * @generated
 */
@JSON(strict = true)
public class ServiceFileTemplateModelImpl extends BaseModelImpl<ServiceFileTemplate>
	implements ServiceFileTemplateModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a service file template model instance should use the {@link org.opencps.servicemgt.model.ServiceFileTemplate} interface instead.
	 */
	public static final String TABLE_NAME = "opencps_dictitem";
	public static final Object[][] TABLE_COLUMNS = {
			{ "serviceinfoId", Types.BIGINT },
			{ "templatefileId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table opencps_dictitem (serviceinfoId LONG not null,templatefileId LONG not null,primary key (serviceinfoId, templatefileId))";
	public static final String TABLE_SQL_DROP = "drop table opencps_dictitem";
	public static final String ORDER_BY_JPQL = " ORDER BY serviceFileTemplate.id.serviceinfoId ASC, serviceFileTemplate.id.templatefileId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY opencps_dictitem.serviceinfoId ASC, opencps_dictitem.templatefileId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.opencps.servicemgt.model.ServiceFileTemplate"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.opencps.servicemgt.model.ServiceFileTemplate"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.opencps.servicemgt.model.ServiceFileTemplate"),
			true);
	public static long SERVICEINFOID_COLUMN_BITMASK = 1L;
	public static long TEMPLATEFILEID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ServiceFileTemplate toModel(ServiceFileTemplateSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ServiceFileTemplate model = new ServiceFileTemplateImpl();

		model.setServiceinfoId(soapModel.getServiceinfoId());
		model.setTemplatefileId(soapModel.getTemplatefileId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ServiceFileTemplate> toModels(
		ServiceFileTemplateSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ServiceFileTemplate> models = new ArrayList<ServiceFileTemplate>(soapModels.length);

		for (ServiceFileTemplateSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.opencps.servicemgt.model.ServiceFileTemplate"));

	public ServiceFileTemplateModelImpl() {
	}

	@Override
	public ServiceFileTemplatePK getPrimaryKey() {
		return new ServiceFileTemplatePK(_serviceinfoId, _templatefileId);
	}

	@Override
	public void setPrimaryKey(ServiceFileTemplatePK primaryKey) {
		setServiceinfoId(primaryKey.serviceinfoId);
		setTemplatefileId(primaryKey.templatefileId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new ServiceFileTemplatePK(_serviceinfoId, _templatefileId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((ServiceFileTemplatePK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return ServiceFileTemplate.class;
	}

	@Override
	public String getModelClassName() {
		return ServiceFileTemplate.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("serviceinfoId", getServiceinfoId());
		attributes.put("templatefileId", getTemplatefileId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long serviceinfoId = (Long)attributes.get("serviceinfoId");

		if (serviceinfoId != null) {
			setServiceinfoId(serviceinfoId);
		}

		Long templatefileId = (Long)attributes.get("templatefileId");

		if (templatefileId != null) {
			setTemplatefileId(templatefileId);
		}
	}

	@JSON
	@Override
	public long getServiceinfoId() {
		return _serviceinfoId;
	}

	@Override
	public void setServiceinfoId(long serviceinfoId) {
		_columnBitmask |= SERVICEINFOID_COLUMN_BITMASK;

		if (!_setOriginalServiceinfoId) {
			_setOriginalServiceinfoId = true;

			_originalServiceinfoId = _serviceinfoId;
		}

		_serviceinfoId = serviceinfoId;
	}

	public long getOriginalServiceinfoId() {
		return _originalServiceinfoId;
	}

	@JSON
	@Override
	public long getTemplatefileId() {
		return _templatefileId;
	}

	@Override
	public void setTemplatefileId(long templatefileId) {
		_templatefileId = templatefileId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ServiceFileTemplate toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ServiceFileTemplate)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ServiceFileTemplateImpl serviceFileTemplateImpl = new ServiceFileTemplateImpl();

		serviceFileTemplateImpl.setServiceinfoId(getServiceinfoId());
		serviceFileTemplateImpl.setTemplatefileId(getTemplatefileId());

		serviceFileTemplateImpl.resetOriginalValues();

		return serviceFileTemplateImpl;
	}

	@Override
	public int compareTo(ServiceFileTemplate serviceFileTemplate) {
		ServiceFileTemplatePK primaryKey = serviceFileTemplate.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ServiceFileTemplate)) {
			return false;
		}

		ServiceFileTemplate serviceFileTemplate = (ServiceFileTemplate)obj;

		ServiceFileTemplatePK primaryKey = serviceFileTemplate.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
		ServiceFileTemplateModelImpl serviceFileTemplateModelImpl = this;

		serviceFileTemplateModelImpl._originalServiceinfoId = serviceFileTemplateModelImpl._serviceinfoId;

		serviceFileTemplateModelImpl._setOriginalServiceinfoId = false;

		serviceFileTemplateModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ServiceFileTemplate> toCacheModel() {
		ServiceFileTemplateCacheModel serviceFileTemplateCacheModel = new ServiceFileTemplateCacheModel();

		serviceFileTemplateCacheModel.serviceinfoId = getServiceinfoId();

		serviceFileTemplateCacheModel.templatefileId = getTemplatefileId();

		return serviceFileTemplateCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{serviceinfoId=");
		sb.append(getServiceinfoId());
		sb.append(", templatefileId=");
		sb.append(getTemplatefileId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("org.opencps.servicemgt.model.ServiceFileTemplate");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>serviceinfoId</column-name><column-value><![CDATA[");
		sb.append(getServiceinfoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>templatefileId</column-name><column-value><![CDATA[");
		sb.append(getTemplatefileId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ServiceFileTemplate.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ServiceFileTemplate.class
		};
	private long _serviceinfoId;
	private long _originalServiceinfoId;
	private boolean _setOriginalServiceinfoId;
	private long _templatefileId;
	private long _columnBitmask;
	private ServiceFileTemplate _escapedModel;
}