/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.opencps.usermgt.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.persistence.UserPersistence;

import org.opencps.usermgt.model.JobPos;
import org.opencps.usermgt.service.JobPosLocalService;
import org.opencps.usermgt.service.persistence.EmployeePersistence;
import org.opencps.usermgt.service.persistence.JobPosPersistence;
import org.opencps.usermgt.service.persistence.WorkingUnitFinder;
import org.opencps.usermgt.service.persistence.WorkingUnitPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the job pos local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link org.opencps.usermgt.service.impl.JobPosLocalServiceImpl}.
 * </p>
 *
 * @author khoavd
 * @see org.opencps.usermgt.service.impl.JobPosLocalServiceImpl
 * @see org.opencps.usermgt.service.JobPosLocalServiceUtil
 * @generated
 */
public abstract class JobPosLocalServiceBaseImpl extends BaseLocalServiceImpl
	implements JobPosLocalService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link org.opencps.usermgt.service.JobPosLocalServiceUtil} to access the job pos local service.
	 */

	/**
	 * Adds the job pos to the database. Also notifies the appropriate model listeners.
	 *
	 * @param jobPos the job pos
	 * @return the job pos that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public JobPos addJobPos(JobPos jobPos) throws SystemException {
		jobPos.setNew(true);

		return jobPosPersistence.update(jobPos);
	}

	/**
	 * Creates a new job pos with the primary key. Does not add the job pos to the database.
	 *
	 * @param jobPosId the primary key for the new job pos
	 * @return the new job pos
	 */
	@Override
	public JobPos createJobPos(long jobPosId) {
		return jobPosPersistence.create(jobPosId);
	}

	/**
	 * Deletes the job pos with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param jobPosId the primary key of the job pos
	 * @return the job pos that was removed
	 * @throws PortalException if a job pos with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public JobPos deleteJobPos(long jobPosId)
		throws PortalException, SystemException {
		return jobPosPersistence.remove(jobPosId);
	}

	/**
	 * Deletes the job pos from the database. Also notifies the appropriate model listeners.
	 *
	 * @param jobPos the job pos
	 * @return the job pos that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public JobPos deleteJobPos(JobPos jobPos) throws SystemException {
		return jobPosPersistence.remove(jobPos);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(JobPos.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return jobPosPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link org.opencps.usermgt.model.impl.JobPosModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return jobPosPersistence.findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link org.opencps.usermgt.model.impl.JobPosModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return jobPosPersistence.findWithDynamicQuery(dynamicQuery, start, end,
			orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return jobPosPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) throws SystemException {
		return jobPosPersistence.countWithDynamicQuery(dynamicQuery, projection);
	}

	@Override
	public JobPos fetchJobPos(long jobPosId) throws SystemException {
		return jobPosPersistence.fetchByPrimaryKey(jobPosId);
	}

	/**
	 * Returns the job pos with the primary key.
	 *
	 * @param jobPosId the primary key of the job pos
	 * @return the job pos
	 * @throws PortalException if a job pos with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public JobPos getJobPos(long jobPosId)
		throws PortalException, SystemException {
		return jobPosPersistence.findByPrimaryKey(jobPosId);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return jobPosPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the job poses.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link org.opencps.usermgt.model.impl.JobPosModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of job poses
	 * @param end the upper bound of the range of job poses (not inclusive)
	 * @return the range of job poses
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public List<JobPos> getJobPoses(int start, int end)
		throws SystemException {
		return jobPosPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of job poses.
	 *
	 * @return the number of job poses
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public int getJobPosesCount() throws SystemException {
		return jobPosPersistence.countAll();
	}

	/**
	 * Updates the job pos in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param jobPos the job pos
	 * @return the job pos that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public JobPos updateJobPos(JobPos jobPos) throws SystemException {
		return jobPosPersistence.update(jobPos);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public void addEmployeeJobPos(long employeeId, long jobPosId)
		throws SystemException {
		employeePersistence.addJobPos(employeeId, jobPosId);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public void addEmployeeJobPos(long employeeId, JobPos jobPos)
		throws SystemException {
		employeePersistence.addJobPos(employeeId, jobPos);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public void addEmployeeJobPoses(long employeeId, long[] jobPosIds)
		throws SystemException {
		employeePersistence.addJobPoses(employeeId, jobPosIds);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public void addEmployeeJobPoses(long employeeId, List<JobPos> JobPoses)
		throws SystemException {
		employeePersistence.addJobPoses(employeeId, JobPoses);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public void clearEmployeeJobPoses(long employeeId)
		throws SystemException {
		employeePersistence.clearJobPoses(employeeId);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public void deleteEmployeeJobPos(long employeeId, long jobPosId)
		throws SystemException {
		employeePersistence.removeJobPos(employeeId, jobPosId);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public void deleteEmployeeJobPos(long employeeId, JobPos jobPos)
		throws SystemException {
		employeePersistence.removeJobPos(employeeId, jobPos);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public void deleteEmployeeJobPoses(long employeeId, long[] jobPosIds)
		throws SystemException {
		employeePersistence.removeJobPoses(employeeId, jobPosIds);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public void deleteEmployeeJobPoses(long employeeId, List<JobPos> JobPoses)
		throws SystemException {
		employeePersistence.removeJobPoses(employeeId, JobPoses);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public List<JobPos> getEmployeeJobPoses(long employeeId)
		throws SystemException {
		return employeePersistence.getJobPoses(employeeId);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public List<JobPos> getEmployeeJobPoses(long employeeId, int start, int end)
		throws SystemException {
		return employeePersistence.getJobPoses(employeeId, start, end);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public List<JobPos> getEmployeeJobPoses(long employeeId, int start,
		int end, OrderByComparator orderByComparator) throws SystemException {
		return employeePersistence.getJobPoses(employeeId, start, end,
			orderByComparator);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public int getEmployeeJobPosesCount(long employeeId)
		throws SystemException {
		return employeePersistence.getJobPosesSize(employeeId);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public boolean hasEmployeeJobPos(long employeeId, long jobPosId)
		throws SystemException {
		return employeePersistence.containsJobPos(employeeId, jobPosId);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public boolean hasEmployeeJobPoses(long employeeId)
		throws SystemException {
		return employeePersistence.containsJobPoses(employeeId);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public void setEmployeeJobPoses(long employeeId, long[] jobPosIds)
		throws SystemException {
		employeePersistence.setJobPoses(employeeId, jobPosIds);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public void addWorkingUnitJobPos(long workingunitId, long jobPosId)
		throws SystemException {
		workingUnitPersistence.addJobPos(workingunitId, jobPosId);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public void addWorkingUnitJobPos(long workingunitId, JobPos jobPos)
		throws SystemException {
		workingUnitPersistence.addJobPos(workingunitId, jobPos);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public void addWorkingUnitJobPoses(long workingunitId, long[] jobPosIds)
		throws SystemException {
		workingUnitPersistence.addJobPoses(workingunitId, jobPosIds);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public void addWorkingUnitJobPoses(long workingunitId, List<JobPos> JobPoses)
		throws SystemException {
		workingUnitPersistence.addJobPoses(workingunitId, JobPoses);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public void clearWorkingUnitJobPoses(long workingunitId)
		throws SystemException {
		workingUnitPersistence.clearJobPoses(workingunitId);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public void deleteWorkingUnitJobPos(long workingunitId, long jobPosId)
		throws SystemException {
		workingUnitPersistence.removeJobPos(workingunitId, jobPosId);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public void deleteWorkingUnitJobPos(long workingunitId, JobPos jobPos)
		throws SystemException {
		workingUnitPersistence.removeJobPos(workingunitId, jobPos);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public void deleteWorkingUnitJobPoses(long workingunitId, long[] jobPosIds)
		throws SystemException {
		workingUnitPersistence.removeJobPoses(workingunitId, jobPosIds);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public void deleteWorkingUnitJobPoses(long workingunitId,
		List<JobPos> JobPoses) throws SystemException {
		workingUnitPersistence.removeJobPoses(workingunitId, JobPoses);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public List<JobPos> getWorkingUnitJobPoses(long workingunitId)
		throws SystemException {
		return workingUnitPersistence.getJobPoses(workingunitId);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public List<JobPos> getWorkingUnitJobPoses(long workingunitId, int start,
		int end) throws SystemException {
		return workingUnitPersistence.getJobPoses(workingunitId, start, end);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public List<JobPos> getWorkingUnitJobPoses(long workingunitId, int start,
		int end, OrderByComparator orderByComparator) throws SystemException {
		return workingUnitPersistence.getJobPoses(workingunitId, start, end,
			orderByComparator);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public int getWorkingUnitJobPosesCount(long workingunitId)
		throws SystemException {
		return workingUnitPersistence.getJobPosesSize(workingunitId);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public boolean hasWorkingUnitJobPos(long workingunitId, long jobPosId)
		throws SystemException {
		return workingUnitPersistence.containsJobPos(workingunitId, jobPosId);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public boolean hasWorkingUnitJobPoses(long workingunitId)
		throws SystemException {
		return workingUnitPersistence.containsJobPoses(workingunitId);
	}

	/**
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public void setWorkingUnitJobPoses(long workingunitId, long[] jobPosIds)
		throws SystemException {
		workingUnitPersistence.setJobPoses(workingunitId, jobPosIds);
	}

	/**
	 * Returns the employee local service.
	 *
	 * @return the employee local service
	 */
	public org.opencps.usermgt.service.EmployeeLocalService getEmployeeLocalService() {
		return employeeLocalService;
	}

	/**
	 * Sets the employee local service.
	 *
	 * @param employeeLocalService the employee local service
	 */
	public void setEmployeeLocalService(
		org.opencps.usermgt.service.EmployeeLocalService employeeLocalService) {
		this.employeeLocalService = employeeLocalService;
	}

	/**
	 * Returns the employee remote service.
	 *
	 * @return the employee remote service
	 */
	public org.opencps.usermgt.service.EmployeeService getEmployeeService() {
		return employeeService;
	}

	/**
	 * Sets the employee remote service.
	 *
	 * @param employeeService the employee remote service
	 */
	public void setEmployeeService(
		org.opencps.usermgt.service.EmployeeService employeeService) {
		this.employeeService = employeeService;
	}

	/**
	 * Returns the employee persistence.
	 *
	 * @return the employee persistence
	 */
	public EmployeePersistence getEmployeePersistence() {
		return employeePersistence;
	}

	/**
	 * Sets the employee persistence.
	 *
	 * @param employeePersistence the employee persistence
	 */
	public void setEmployeePersistence(EmployeePersistence employeePersistence) {
		this.employeePersistence = employeePersistence;
	}

	/**
	 * Returns the job pos local service.
	 *
	 * @return the job pos local service
	 */
	public org.opencps.usermgt.service.JobPosLocalService getJobPosLocalService() {
		return jobPosLocalService;
	}

	/**
	 * Sets the job pos local service.
	 *
	 * @param jobPosLocalService the job pos local service
	 */
	public void setJobPosLocalService(
		org.opencps.usermgt.service.JobPosLocalService jobPosLocalService) {
		this.jobPosLocalService = jobPosLocalService;
	}

	/**
	 * Returns the job pos remote service.
	 *
	 * @return the job pos remote service
	 */
	public org.opencps.usermgt.service.JobPosService getJobPosService() {
		return jobPosService;
	}

	/**
	 * Sets the job pos remote service.
	 *
	 * @param jobPosService the job pos remote service
	 */
	public void setJobPosService(
		org.opencps.usermgt.service.JobPosService jobPosService) {
		this.jobPosService = jobPosService;
	}

	/**
	 * Returns the job pos persistence.
	 *
	 * @return the job pos persistence
	 */
	public JobPosPersistence getJobPosPersistence() {
		return jobPosPersistence;
	}

	/**
	 * Sets the job pos persistence.
	 *
	 * @param jobPosPersistence the job pos persistence
	 */
	public void setJobPosPersistence(JobPosPersistence jobPosPersistence) {
		this.jobPosPersistence = jobPosPersistence;
	}

	/**
	 * Returns the working unit local service.
	 *
	 * @return the working unit local service
	 */
	public org.opencps.usermgt.service.WorkingUnitLocalService getWorkingUnitLocalService() {
		return workingUnitLocalService;
	}

	/**
	 * Sets the working unit local service.
	 *
	 * @param workingUnitLocalService the working unit local service
	 */
	public void setWorkingUnitLocalService(
		org.opencps.usermgt.service.WorkingUnitLocalService workingUnitLocalService) {
		this.workingUnitLocalService = workingUnitLocalService;
	}

	/**
	 * Returns the working unit remote service.
	 *
	 * @return the working unit remote service
	 */
	public org.opencps.usermgt.service.WorkingUnitService getWorkingUnitService() {
		return workingUnitService;
	}

	/**
	 * Sets the working unit remote service.
	 *
	 * @param workingUnitService the working unit remote service
	 */
	public void setWorkingUnitService(
		org.opencps.usermgt.service.WorkingUnitService workingUnitService) {
		this.workingUnitService = workingUnitService;
	}

	/**
	 * Returns the working unit persistence.
	 *
	 * @return the working unit persistence
	 */
	public WorkingUnitPersistence getWorkingUnitPersistence() {
		return workingUnitPersistence;
	}

	/**
	 * Sets the working unit persistence.
	 *
	 * @param workingUnitPersistence the working unit persistence
	 */
	public void setWorkingUnitPersistence(
		WorkingUnitPersistence workingUnitPersistence) {
		this.workingUnitPersistence = workingUnitPersistence;
	}

	/**
	 * Returns the working unit finder.
	 *
	 * @return the working unit finder
	 */
	public WorkingUnitFinder getWorkingUnitFinder() {
		return workingUnitFinder;
	}

	/**
	 * Sets the working unit finder.
	 *
	 * @param workingUnitFinder the working unit finder
	 */
	public void setWorkingUnitFinder(WorkingUnitFinder workingUnitFinder) {
		this.workingUnitFinder = workingUnitFinder;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();

		PersistedModelLocalServiceRegistryUtil.register("org.opencps.usermgt.model.JobPos",
			jobPosLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"org.opencps.usermgt.model.JobPos");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return JobPos.class;
	}

	protected String getModelClassName() {
		return JobPos.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = jobPosPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = org.opencps.usermgt.service.EmployeeLocalService.class)
	protected org.opencps.usermgt.service.EmployeeLocalService employeeLocalService;
	@BeanReference(type = org.opencps.usermgt.service.EmployeeService.class)
	protected org.opencps.usermgt.service.EmployeeService employeeService;
	@BeanReference(type = EmployeePersistence.class)
	protected EmployeePersistence employeePersistence;
	@BeanReference(type = org.opencps.usermgt.service.JobPosLocalService.class)
	protected org.opencps.usermgt.service.JobPosLocalService jobPosLocalService;
	@BeanReference(type = org.opencps.usermgt.service.JobPosService.class)
	protected org.opencps.usermgt.service.JobPosService jobPosService;
	@BeanReference(type = JobPosPersistence.class)
	protected JobPosPersistence jobPosPersistence;
	@BeanReference(type = org.opencps.usermgt.service.WorkingUnitLocalService.class)
	protected org.opencps.usermgt.service.WorkingUnitLocalService workingUnitLocalService;
	@BeanReference(type = org.opencps.usermgt.service.WorkingUnitService.class)
	protected org.opencps.usermgt.service.WorkingUnitService workingUnitService;
	@BeanReference(type = WorkingUnitPersistence.class)
	protected WorkingUnitPersistence workingUnitPersistence;
	@BeanReference(type = WorkingUnitFinder.class)
	protected WorkingUnitFinder workingUnitFinder;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private JobPosLocalServiceClpInvoker _clpInvoker = new JobPosLocalServiceClpInvoker();
}