/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.opencps.statisticsmgt.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.opencps.statisticsmgt.model.GovagencyLevel;
import org.opencps.statisticsmgt.model.GovagencyLevelModel;
import org.opencps.statisticsmgt.model.GovagencyLevelSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the GovagencyLevel service. Represents a row in the &quot;opencps_govagencylevel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.opencps.statisticsmgt.model.GovagencyLevelModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GovagencyLevelImpl}.
 * </p>
 *
 * @author trungnt
 * @see GovagencyLevelImpl
 * @see org.opencps.statisticsmgt.model.GovagencyLevel
 * @see org.opencps.statisticsmgt.model.GovagencyLevelModel
 * @generated
 */
@JSON(strict = true)
public class GovagencyLevelModelImpl extends BaseModelImpl<GovagencyLevel>
	implements GovagencyLevelModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a govagency level model instance should use the {@link org.opencps.statisticsmgt.model.GovagencyLevel} interface instead.
	 */
	public static final String TABLE_NAME = "opencps_govagencylevel";
	public static final Object[][] TABLE_COLUMNS = {
			{ "govagencylevel", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "govAgencyCode", Types.VARCHAR },
			{ "administrationLevel", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table opencps_govagencylevel (govagencylevel LONG not null primary key,companyId LONG,groupId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,govAgencyCode VARCHAR(75) null,administrationLevel INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table opencps_govagencylevel";
	public static final String ORDER_BY_JPQL = " ORDER BY govagencyLevel.govagencylevel ASC";
	public static final String ORDER_BY_SQL = " ORDER BY opencps_govagencylevel.govagencylevel ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.opencps.statisticsmgt.model.GovagencyLevel"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.opencps.statisticsmgt.model.GovagencyLevel"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static GovagencyLevel toModel(GovagencyLevelSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		GovagencyLevel model = new GovagencyLevelImpl();

		model.setGovagencylevel(soapModel.getGovagencylevel());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setGovAgencyCode(soapModel.getGovAgencyCode());
		model.setAdministrationLevel(soapModel.getAdministrationLevel());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<GovagencyLevel> toModels(GovagencyLevelSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<GovagencyLevel> models = new ArrayList<GovagencyLevel>(soapModels.length);

		for (GovagencyLevelSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.opencps.statisticsmgt.model.GovagencyLevel"));

	public GovagencyLevelModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _govagencylevel;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setGovagencylevel(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _govagencylevel;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return GovagencyLevel.class;
	}

	@Override
	public String getModelClassName() {
		return GovagencyLevel.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("govagencylevel", getGovagencylevel());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());
		attributes.put("userId", getUserId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("govAgencyCode", getGovAgencyCode());
		attributes.put("administrationLevel", getAdministrationLevel());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long govagencylevel = (Long)attributes.get("govagencylevel");

		if (govagencylevel != null) {
			setGovagencylevel(govagencylevel);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String govAgencyCode = (String)attributes.get("govAgencyCode");

		if (govAgencyCode != null) {
			setGovAgencyCode(govAgencyCode);
		}

		Integer administrationLevel = (Integer)attributes.get(
				"administrationLevel");

		if (administrationLevel != null) {
			setAdministrationLevel(administrationLevel);
		}
	}

	@JSON
	@Override
	public long getGovagencylevel() {
		return _govagencylevel;
	}

	@Override
	public void setGovagencylevel(long govagencylevel) {
		_govagencylevel = govagencylevel;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getGovAgencyCode() {
		if (_govAgencyCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _govAgencyCode;
		}
	}

	@Override
	public void setGovAgencyCode(String govAgencyCode) {
		_govAgencyCode = govAgencyCode;
	}

	@JSON
	@Override
	public int getAdministrationLevel() {
		return _administrationLevel;
	}

	@Override
	public void setAdministrationLevel(int administrationLevel) {
		_administrationLevel = administrationLevel;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			GovagencyLevel.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public GovagencyLevel toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (GovagencyLevel)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		GovagencyLevelImpl govagencyLevelImpl = new GovagencyLevelImpl();

		govagencyLevelImpl.setGovagencylevel(getGovagencylevel());
		govagencyLevelImpl.setCompanyId(getCompanyId());
		govagencyLevelImpl.setGroupId(getGroupId());
		govagencyLevelImpl.setUserId(getUserId());
		govagencyLevelImpl.setCreateDate(getCreateDate());
		govagencyLevelImpl.setModifiedDate(getModifiedDate());
		govagencyLevelImpl.setGovAgencyCode(getGovAgencyCode());
		govagencyLevelImpl.setAdministrationLevel(getAdministrationLevel());

		govagencyLevelImpl.resetOriginalValues();

		return govagencyLevelImpl;
	}

	@Override
	public int compareTo(GovagencyLevel govagencyLevel) {
		long primaryKey = govagencyLevel.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof GovagencyLevel)) {
			return false;
		}

		GovagencyLevel govagencyLevel = (GovagencyLevel)obj;

		long primaryKey = govagencyLevel.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<GovagencyLevel> toCacheModel() {
		GovagencyLevelCacheModel govagencyLevelCacheModel = new GovagencyLevelCacheModel();

		govagencyLevelCacheModel.govagencylevel = getGovagencylevel();

		govagencyLevelCacheModel.companyId = getCompanyId();

		govagencyLevelCacheModel.groupId = getGroupId();

		govagencyLevelCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			govagencyLevelCacheModel.createDate = createDate.getTime();
		}
		else {
			govagencyLevelCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			govagencyLevelCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			govagencyLevelCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		govagencyLevelCacheModel.govAgencyCode = getGovAgencyCode();

		String govAgencyCode = govagencyLevelCacheModel.govAgencyCode;

		if ((govAgencyCode != null) && (govAgencyCode.length() == 0)) {
			govagencyLevelCacheModel.govAgencyCode = null;
		}

		govagencyLevelCacheModel.administrationLevel = getAdministrationLevel();

		return govagencyLevelCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{govagencylevel=");
		sb.append(getGovagencylevel());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", govAgencyCode=");
		sb.append(getGovAgencyCode());
		sb.append(", administrationLevel=");
		sb.append(getAdministrationLevel());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("org.opencps.statisticsmgt.model.GovagencyLevel");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>govagencylevel</column-name><column-value><![CDATA[");
		sb.append(getGovagencylevel());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>govAgencyCode</column-name><column-value><![CDATA[");
		sb.append(getGovAgencyCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>administrationLevel</column-name><column-value><![CDATA[");
		sb.append(getAdministrationLevel());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = GovagencyLevel.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			GovagencyLevel.class
		};
	private long _govagencylevel;
	private long _companyId;
	private long _groupId;
	private long _userId;
	private String _userUuid;
	private Date _createDate;
	private Date _modifiedDate;
	private String _govAgencyCode;
	private int _administrationLevel;
	private GovagencyLevel _escapedModel;
}