/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.opencps.accountmgt.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.opencps.accountmgt.model.Business;
import org.opencps.accountmgt.model.BusinessModel;
import org.opencps.accountmgt.model.BusinessSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Business service. Represents a row in the &quot;opencps_acc_business&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.opencps.accountmgt.model.BusinessModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BusinessImpl}.
 * </p>
 *
 * @author khoavd
 * @see BusinessImpl
 * @see org.opencps.accountmgt.model.Business
 * @see org.opencps.accountmgt.model.BusinessModel
 * @generated
 */
@JSON(strict = true)
public class BusinessModelImpl extends BaseModelImpl<Business>
	implements BusinessModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a business model instance should use the {@link org.opencps.accountmgt.model.Business} interface instead.
	 */
	public static final String TABLE_NAME = "opencps_acc_business";
	public static final Object[][] TABLE_COLUMNS = {
			{ "businessId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "uuid_", Types.VARCHAR },
			{ "name", Types.VARCHAR },
			{ "enName", Types.VARCHAR },
			{ "shortName", Types.VARCHAR },
			{ "businessType", Types.VARCHAR },
			{ "idNumber", Types.VARCHAR },
			{ "address", Types.VARCHAR },
			{ "cityCode", Types.VARCHAR },
			{ "districtCode", Types.VARCHAR },
			{ "wardCode", Types.VARCHAR },
			{ "telNo", Types.VARCHAR },
			{ "email", Types.VARCHAR },
			{ "representativeName", Types.VARCHAR },
			{ "representativeRole", Types.VARCHAR },
			{ "attachFile", Types.BIGINT },
			{ "mappingOrganizationId", Types.BIGINT },
			{ "mappingUserId", Types.BIGINT },
			{ "accountStatus", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table opencps_acc_business (businessId LONG not null primary key,companyId LONG,groupId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,uuid_ VARCHAR(75) null,name VARCHAR(75) null,enName VARCHAR(75) null,shortName VARCHAR(75) null,businessType VARCHAR(75) null,idNumber VARCHAR(75) null,address VARCHAR(75) null,cityCode VARCHAR(75) null,districtCode VARCHAR(75) null,wardCode VARCHAR(75) null,telNo VARCHAR(75) null,email VARCHAR(75) null,representativeName VARCHAR(75) null,representativeRole VARCHAR(75) null,attachFile LONG,mappingOrganizationId LONG,mappingUserId LONG,accountStatus INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table opencps_acc_business";
	public static final String ORDER_BY_JPQL = " ORDER BY business.createDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY opencps_acc_business.createDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.opencps.accountmgt.model.Business"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.opencps.accountmgt.model.Business"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.opencps.accountmgt.model.Business"),
			true);
	public static long ACCOUNTSTATUS_COLUMN_BITMASK = 1L;
	public static long BUSINESSTYPE_COLUMN_BITMASK = 2L;
	public static long CITYCODE_COLUMN_BITMASK = 4L;
	public static long DISTRICTCODE_COLUMN_BITMASK = 8L;
	public static long GROUPID_COLUMN_BITMASK = 16L;
	public static long CREATEDATE_COLUMN_BITMASK = 32L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Business toModel(BusinessSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Business model = new BusinessImpl();

		model.setBusinessId(soapModel.getBusinessId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setUuid(soapModel.getUuid());
		model.setName(soapModel.getName());
		model.setEnName(soapModel.getEnName());
		model.setShortName(soapModel.getShortName());
		model.setBusinessType(soapModel.getBusinessType());
		model.setIdNumber(soapModel.getIdNumber());
		model.setAddress(soapModel.getAddress());
		model.setCityCode(soapModel.getCityCode());
		model.setDistrictCode(soapModel.getDistrictCode());
		model.setWardCode(soapModel.getWardCode());
		model.setTelNo(soapModel.getTelNo());
		model.setEmail(soapModel.getEmail());
		model.setRepresentativeName(soapModel.getRepresentativeName());
		model.setRepresentativeRole(soapModel.getRepresentativeRole());
		model.setAttachFile(soapModel.getAttachFile());
		model.setMappingOrganizationId(soapModel.getMappingOrganizationId());
		model.setMappingUserId(soapModel.getMappingUserId());
		model.setAccountStatus(soapModel.getAccountStatus());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Business> toModels(BusinessSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Business> models = new ArrayList<Business>(soapModels.length);

		for (BusinessSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.opencps.accountmgt.model.Business"));

	public BusinessModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _businessId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBusinessId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _businessId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Business.class;
	}

	@Override
	public String getModelClassName() {
		return Business.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("businessId", getBusinessId());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());
		attributes.put("userId", getUserId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("uuid", getUuid());
		attributes.put("name", getName());
		attributes.put("enName", getEnName());
		attributes.put("shortName", getShortName());
		attributes.put("businessType", getBusinessType());
		attributes.put("idNumber", getIdNumber());
		attributes.put("address", getAddress());
		attributes.put("cityCode", getCityCode());
		attributes.put("districtCode", getDistrictCode());
		attributes.put("wardCode", getWardCode());
		attributes.put("telNo", getTelNo());
		attributes.put("email", getEmail());
		attributes.put("representativeName", getRepresentativeName());
		attributes.put("representativeRole", getRepresentativeRole());
		attributes.put("attachFile", getAttachFile());
		attributes.put("mappingOrganizationId", getMappingOrganizationId());
		attributes.put("mappingUserId", getMappingUserId());
		attributes.put("accountStatus", getAccountStatus());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long businessId = (Long)attributes.get("businessId");

		if (businessId != null) {
			setBusinessId(businessId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String enName = (String)attributes.get("enName");

		if (enName != null) {
			setEnName(enName);
		}

		String shortName = (String)attributes.get("shortName");

		if (shortName != null) {
			setShortName(shortName);
		}

		String businessType = (String)attributes.get("businessType");

		if (businessType != null) {
			setBusinessType(businessType);
		}

		String idNumber = (String)attributes.get("idNumber");

		if (idNumber != null) {
			setIdNumber(idNumber);
		}

		String address = (String)attributes.get("address");

		if (address != null) {
			setAddress(address);
		}

		String cityCode = (String)attributes.get("cityCode");

		if (cityCode != null) {
			setCityCode(cityCode);
		}

		String districtCode = (String)attributes.get("districtCode");

		if (districtCode != null) {
			setDistrictCode(districtCode);
		}

		String wardCode = (String)attributes.get("wardCode");

		if (wardCode != null) {
			setWardCode(wardCode);
		}

		String telNo = (String)attributes.get("telNo");

		if (telNo != null) {
			setTelNo(telNo);
		}

		String email = (String)attributes.get("email");

		if (email != null) {
			setEmail(email);
		}

		String representativeName = (String)attributes.get("representativeName");

		if (representativeName != null) {
			setRepresentativeName(representativeName);
		}

		String representativeRole = (String)attributes.get("representativeRole");

		if (representativeRole != null) {
			setRepresentativeRole(representativeRole);
		}

		Long attachFile = (Long)attributes.get("attachFile");

		if (attachFile != null) {
			setAttachFile(attachFile);
		}

		Long mappingOrganizationId = (Long)attributes.get(
				"mappingOrganizationId");

		if (mappingOrganizationId != null) {
			setMappingOrganizationId(mappingOrganizationId);
		}

		Long mappingUserId = (Long)attributes.get("mappingUserId");

		if (mappingUserId != null) {
			setMappingUserId(mappingUserId);
		}

		Integer accountStatus = (Integer)attributes.get("accountStatus");

		if (accountStatus != null) {
			setAccountStatus(accountStatus);
		}
	}

	@JSON
	@Override
	public long getBusinessId() {
		return _businessId;
	}

	@Override
	public void setBusinessId(long businessId) {
		_businessId = businessId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_uuid = uuid;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@JSON
	@Override
	public String getEnName() {
		if (_enName == null) {
			return StringPool.BLANK;
		}
		else {
			return _enName;
		}
	}

	@Override
	public void setEnName(String enName) {
		_enName = enName;
	}

	@JSON
	@Override
	public String getShortName() {
		if (_shortName == null) {
			return StringPool.BLANK;
		}
		else {
			return _shortName;
		}
	}

	@Override
	public void setShortName(String shortName) {
		_shortName = shortName;
	}

	@JSON
	@Override
	public String getBusinessType() {
		if (_businessType == null) {
			return StringPool.BLANK;
		}
		else {
			return _businessType;
		}
	}

	@Override
	public void setBusinessType(String businessType) {
		_columnBitmask |= BUSINESSTYPE_COLUMN_BITMASK;

		if (_originalBusinessType == null) {
			_originalBusinessType = _businessType;
		}

		_businessType = businessType;
	}

	public String getOriginalBusinessType() {
		return GetterUtil.getString(_originalBusinessType);
	}

	@JSON
	@Override
	public String getIdNumber() {
		if (_idNumber == null) {
			return StringPool.BLANK;
		}
		else {
			return _idNumber;
		}
	}

	@Override
	public void setIdNumber(String idNumber) {
		_idNumber = idNumber;
	}

	@JSON
	@Override
	public String getAddress() {
		if (_address == null) {
			return StringPool.BLANK;
		}
		else {
			return _address;
		}
	}

	@Override
	public void setAddress(String address) {
		_address = address;
	}

	@JSON
	@Override
	public String getCityCode() {
		if (_cityCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _cityCode;
		}
	}

	@Override
	public void setCityCode(String cityCode) {
		_columnBitmask |= CITYCODE_COLUMN_BITMASK;

		if (_originalCityCode == null) {
			_originalCityCode = _cityCode;
		}

		_cityCode = cityCode;
	}

	public String getOriginalCityCode() {
		return GetterUtil.getString(_originalCityCode);
	}

	@JSON
	@Override
	public String getDistrictCode() {
		if (_districtCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _districtCode;
		}
	}

	@Override
	public void setDistrictCode(String districtCode) {
		_columnBitmask |= DISTRICTCODE_COLUMN_BITMASK;

		if (_originalDistrictCode == null) {
			_originalDistrictCode = _districtCode;
		}

		_districtCode = districtCode;
	}

	public String getOriginalDistrictCode() {
		return GetterUtil.getString(_originalDistrictCode);
	}

	@JSON
	@Override
	public String getWardCode() {
		if (_wardCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _wardCode;
		}
	}

	@Override
	public void setWardCode(String wardCode) {
		_wardCode = wardCode;
	}

	@JSON
	@Override
	public String getTelNo() {
		if (_telNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _telNo;
		}
	}

	@Override
	public void setTelNo(String telNo) {
		_telNo = telNo;
	}

	@JSON
	@Override
	public String getEmail() {
		if (_email == null) {
			return StringPool.BLANK;
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		_email = email;
	}

	@JSON
	@Override
	public String getRepresentativeName() {
		if (_representativeName == null) {
			return StringPool.BLANK;
		}
		else {
			return _representativeName;
		}
	}

	@Override
	public void setRepresentativeName(String representativeName) {
		_representativeName = representativeName;
	}

	@JSON
	@Override
	public String getRepresentativeRole() {
		if (_representativeRole == null) {
			return StringPool.BLANK;
		}
		else {
			return _representativeRole;
		}
	}

	@Override
	public void setRepresentativeRole(String representativeRole) {
		_representativeRole = representativeRole;
	}

	@JSON
	@Override
	public long getAttachFile() {
		return _attachFile;
	}

	@Override
	public void setAttachFile(long attachFile) {
		_attachFile = attachFile;
	}

	@JSON
	@Override
	public long getMappingOrganizationId() {
		return _mappingOrganizationId;
	}

	@Override
	public void setMappingOrganizationId(long mappingOrganizationId) {
		_mappingOrganizationId = mappingOrganizationId;
	}

	@JSON
	@Override
	public long getMappingUserId() {
		return _mappingUserId;
	}

	@Override
	public void setMappingUserId(long mappingUserId) {
		_mappingUserId = mappingUserId;
	}

	@Override
	public String getMappingUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getMappingUserId(), "uuid",
			_mappingUserUuid);
	}

	@Override
	public void setMappingUserUuid(String mappingUserUuid) {
		_mappingUserUuid = mappingUserUuid;
	}

	@JSON
	@Override
	public int getAccountStatus() {
		return _accountStatus;
	}

	@Override
	public void setAccountStatus(int accountStatus) {
		_columnBitmask |= ACCOUNTSTATUS_COLUMN_BITMASK;

		if (!_setOriginalAccountStatus) {
			_setOriginalAccountStatus = true;

			_originalAccountStatus = _accountStatus;
		}

		_accountStatus = accountStatus;
	}

	public int getOriginalAccountStatus() {
		return _originalAccountStatus;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Business.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Business toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Business)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BusinessImpl businessImpl = new BusinessImpl();

		businessImpl.setBusinessId(getBusinessId());
		businessImpl.setCompanyId(getCompanyId());
		businessImpl.setGroupId(getGroupId());
		businessImpl.setUserId(getUserId());
		businessImpl.setCreateDate(getCreateDate());
		businessImpl.setModifiedDate(getModifiedDate());
		businessImpl.setUuid(getUuid());
		businessImpl.setName(getName());
		businessImpl.setEnName(getEnName());
		businessImpl.setShortName(getShortName());
		businessImpl.setBusinessType(getBusinessType());
		businessImpl.setIdNumber(getIdNumber());
		businessImpl.setAddress(getAddress());
		businessImpl.setCityCode(getCityCode());
		businessImpl.setDistrictCode(getDistrictCode());
		businessImpl.setWardCode(getWardCode());
		businessImpl.setTelNo(getTelNo());
		businessImpl.setEmail(getEmail());
		businessImpl.setRepresentativeName(getRepresentativeName());
		businessImpl.setRepresentativeRole(getRepresentativeRole());
		businessImpl.setAttachFile(getAttachFile());
		businessImpl.setMappingOrganizationId(getMappingOrganizationId());
		businessImpl.setMappingUserId(getMappingUserId());
		businessImpl.setAccountStatus(getAccountStatus());

		businessImpl.resetOriginalValues();

		return businessImpl;
	}

	@Override
	public int compareTo(Business business) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(), business.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Business)) {
			return false;
		}

		Business business = (Business)obj;

		long primaryKey = business.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		BusinessModelImpl businessModelImpl = this;

		businessModelImpl._originalGroupId = businessModelImpl._groupId;

		businessModelImpl._setOriginalGroupId = false;

		businessModelImpl._originalBusinessType = businessModelImpl._businessType;

		businessModelImpl._originalCityCode = businessModelImpl._cityCode;

		businessModelImpl._originalDistrictCode = businessModelImpl._districtCode;

		businessModelImpl._originalAccountStatus = businessModelImpl._accountStatus;

		businessModelImpl._setOriginalAccountStatus = false;

		businessModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Business> toCacheModel() {
		BusinessCacheModel businessCacheModel = new BusinessCacheModel();

		businessCacheModel.businessId = getBusinessId();

		businessCacheModel.companyId = getCompanyId();

		businessCacheModel.groupId = getGroupId();

		businessCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			businessCacheModel.createDate = createDate.getTime();
		}
		else {
			businessCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			businessCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			businessCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		businessCacheModel.uuid = getUuid();

		String uuid = businessCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			businessCacheModel.uuid = null;
		}

		businessCacheModel.name = getName();

		String name = businessCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			businessCacheModel.name = null;
		}

		businessCacheModel.enName = getEnName();

		String enName = businessCacheModel.enName;

		if ((enName != null) && (enName.length() == 0)) {
			businessCacheModel.enName = null;
		}

		businessCacheModel.shortName = getShortName();

		String shortName = businessCacheModel.shortName;

		if ((shortName != null) && (shortName.length() == 0)) {
			businessCacheModel.shortName = null;
		}

		businessCacheModel.businessType = getBusinessType();

		String businessType = businessCacheModel.businessType;

		if ((businessType != null) && (businessType.length() == 0)) {
			businessCacheModel.businessType = null;
		}

		businessCacheModel.idNumber = getIdNumber();

		String idNumber = businessCacheModel.idNumber;

		if ((idNumber != null) && (idNumber.length() == 0)) {
			businessCacheModel.idNumber = null;
		}

		businessCacheModel.address = getAddress();

		String address = businessCacheModel.address;

		if ((address != null) && (address.length() == 0)) {
			businessCacheModel.address = null;
		}

		businessCacheModel.cityCode = getCityCode();

		String cityCode = businessCacheModel.cityCode;

		if ((cityCode != null) && (cityCode.length() == 0)) {
			businessCacheModel.cityCode = null;
		}

		businessCacheModel.districtCode = getDistrictCode();

		String districtCode = businessCacheModel.districtCode;

		if ((districtCode != null) && (districtCode.length() == 0)) {
			businessCacheModel.districtCode = null;
		}

		businessCacheModel.wardCode = getWardCode();

		String wardCode = businessCacheModel.wardCode;

		if ((wardCode != null) && (wardCode.length() == 0)) {
			businessCacheModel.wardCode = null;
		}

		businessCacheModel.telNo = getTelNo();

		String telNo = businessCacheModel.telNo;

		if ((telNo != null) && (telNo.length() == 0)) {
			businessCacheModel.telNo = null;
		}

		businessCacheModel.email = getEmail();

		String email = businessCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			businessCacheModel.email = null;
		}

		businessCacheModel.representativeName = getRepresentativeName();

		String representativeName = businessCacheModel.representativeName;

		if ((representativeName != null) && (representativeName.length() == 0)) {
			businessCacheModel.representativeName = null;
		}

		businessCacheModel.representativeRole = getRepresentativeRole();

		String representativeRole = businessCacheModel.representativeRole;

		if ((representativeRole != null) && (representativeRole.length() == 0)) {
			businessCacheModel.representativeRole = null;
		}

		businessCacheModel.attachFile = getAttachFile();

		businessCacheModel.mappingOrganizationId = getMappingOrganizationId();

		businessCacheModel.mappingUserId = getMappingUserId();

		businessCacheModel.accountStatus = getAccountStatus();

		return businessCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(49);

		sb.append("{businessId=");
		sb.append(getBusinessId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", uuid=");
		sb.append(getUuid());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", enName=");
		sb.append(getEnName());
		sb.append(", shortName=");
		sb.append(getShortName());
		sb.append(", businessType=");
		sb.append(getBusinessType());
		sb.append(", idNumber=");
		sb.append(getIdNumber());
		sb.append(", address=");
		sb.append(getAddress());
		sb.append(", cityCode=");
		sb.append(getCityCode());
		sb.append(", districtCode=");
		sb.append(getDistrictCode());
		sb.append(", wardCode=");
		sb.append(getWardCode());
		sb.append(", telNo=");
		sb.append(getTelNo());
		sb.append(", email=");
		sb.append(getEmail());
		sb.append(", representativeName=");
		sb.append(getRepresentativeName());
		sb.append(", representativeRole=");
		sb.append(getRepresentativeRole());
		sb.append(", attachFile=");
		sb.append(getAttachFile());
		sb.append(", mappingOrganizationId=");
		sb.append(getMappingOrganizationId());
		sb.append(", mappingUserId=");
		sb.append(getMappingUserId());
		sb.append(", accountStatus=");
		sb.append(getAccountStatus());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(76);

		sb.append("<model><model-name>");
		sb.append("org.opencps.accountmgt.model.Business");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>businessId</column-name><column-value><![CDATA[");
		sb.append(getBusinessId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>enName</column-name><column-value><![CDATA[");
		sb.append(getEnName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>shortName</column-name><column-value><![CDATA[");
		sb.append(getShortName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>businessType</column-name><column-value><![CDATA[");
		sb.append(getBusinessType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idNumber</column-name><column-value><![CDATA[");
		sb.append(getIdNumber());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>address</column-name><column-value><![CDATA[");
		sb.append(getAddress());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cityCode</column-name><column-value><![CDATA[");
		sb.append(getCityCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>districtCode</column-name><column-value><![CDATA[");
		sb.append(getDistrictCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>wardCode</column-name><column-value><![CDATA[");
		sb.append(getWardCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>telNo</column-name><column-value><![CDATA[");
		sb.append(getTelNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>email</column-name><column-value><![CDATA[");
		sb.append(getEmail());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>representativeName</column-name><column-value><![CDATA[");
		sb.append(getRepresentativeName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>representativeRole</column-name><column-value><![CDATA[");
		sb.append(getRepresentativeRole());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>attachFile</column-name><column-value><![CDATA[");
		sb.append(getAttachFile());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mappingOrganizationId</column-name><column-value><![CDATA[");
		sb.append(getMappingOrganizationId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mappingUserId</column-name><column-value><![CDATA[");
		sb.append(getMappingUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>accountStatus</column-name><column-value><![CDATA[");
		sb.append(getAccountStatus());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Business.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			Business.class
		};
	private long _businessId;
	private long _companyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _userId;
	private String _userUuid;
	private Date _createDate;
	private Date _modifiedDate;
	private String _uuid;
	private String _name;
	private String _enName;
	private String _shortName;
	private String _businessType;
	private String _originalBusinessType;
	private String _idNumber;
	private String _address;
	private String _cityCode;
	private String _originalCityCode;
	private String _districtCode;
	private String _originalDistrictCode;
	private String _wardCode;
	private String _telNo;
	private String _email;
	private String _representativeName;
	private String _representativeRole;
	private long _attachFile;
	private long _mappingOrganizationId;
	private long _mappingUserId;
	private String _mappingUserUuid;
	private int _accountStatus;
	private int _originalAccountStatus;
	private boolean _setOriginalAccountStatus;
	private long _columnBitmask;
	private Business _escapedModel;
}