/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.opencps.accountmgt.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import org.opencps.accountmgt.model.BusinessDomain;
import org.opencps.accountmgt.model.BusinessDomainModel;
import org.opencps.accountmgt.model.BusinessDomainSoap;
import org.opencps.accountmgt.service.persistence.BusinessDomainPK;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the BusinessDomain service. Represents a row in the &quot;opencps_acc_businessdomain&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.opencps.accountmgt.model.BusinessDomainModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BusinessDomainImpl}.
 * </p>
 *
 * @author khoavd
 * @see BusinessDomainImpl
 * @see org.opencps.accountmgt.model.BusinessDomain
 * @see org.opencps.accountmgt.model.BusinessDomainModel
 * @generated
 */
@JSON(strict = true)
public class BusinessDomainModelImpl extends BaseModelImpl<BusinessDomain>
	implements BusinessDomainModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a business domain model instance should use the {@link org.opencps.accountmgt.model.BusinessDomain} interface instead.
	 */
	public static final String TABLE_NAME = "opencps_acc_businessdomain";
	public static final Object[][] TABLE_COLUMNS = {
			{ "businessId", Types.BIGINT },
			{ "businessDomainId", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table opencps_acc_businessdomain (businessId LONG not null,businessDomainId VARCHAR(75) not null,primary key (businessId, businessDomainId))";
	public static final String TABLE_SQL_DROP = "drop table opencps_acc_businessdomain";
	public static final String ORDER_BY_JPQL = " ORDER BY businessDomain.id.businessId ASC, businessDomain.id.businessDomainId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY opencps_acc_businessdomain.businessId ASC, opencps_acc_businessdomain.businessDomainId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.opencps.accountmgt.model.BusinessDomain"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.opencps.accountmgt.model.BusinessDomain"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.opencps.accountmgt.model.BusinessDomain"),
			true);
	public static long BUSINESSDOMAINID_COLUMN_BITMASK = 1L;
	public static long BUSINESSID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static BusinessDomain toModel(BusinessDomainSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		BusinessDomain model = new BusinessDomainImpl();

		model.setBusinessId(soapModel.getBusinessId());
		model.setBusinessDomainId(soapModel.getBusinessDomainId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<BusinessDomain> toModels(BusinessDomainSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<BusinessDomain> models = new ArrayList<BusinessDomain>(soapModels.length);

		for (BusinessDomainSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.opencps.accountmgt.model.BusinessDomain"));

	public BusinessDomainModelImpl() {
	}

	@Override
	public BusinessDomainPK getPrimaryKey() {
		return new BusinessDomainPK(_businessId, _businessDomainId);
	}

	@Override
	public void setPrimaryKey(BusinessDomainPK primaryKey) {
		setBusinessId(primaryKey.businessId);
		setBusinessDomainId(primaryKey.businessDomainId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new BusinessDomainPK(_businessId, _businessDomainId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((BusinessDomainPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return BusinessDomain.class;
	}

	@Override
	public String getModelClassName() {
		return BusinessDomain.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("businessId", getBusinessId());
		attributes.put("businessDomainId", getBusinessDomainId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long businessId = (Long)attributes.get("businessId");

		if (businessId != null) {
			setBusinessId(businessId);
		}

		String businessDomainId = (String)attributes.get("businessDomainId");

		if (businessDomainId != null) {
			setBusinessDomainId(businessDomainId);
		}
	}

	@JSON
	@Override
	public long getBusinessId() {
		return _businessId;
	}

	@Override
	public void setBusinessId(long businessId) {
		_columnBitmask |= BUSINESSID_COLUMN_BITMASK;

		if (!_setOriginalBusinessId) {
			_setOriginalBusinessId = true;

			_originalBusinessId = _businessId;
		}

		_businessId = businessId;
	}

	public long getOriginalBusinessId() {
		return _originalBusinessId;
	}

	@JSON
	@Override
	public String getBusinessDomainId() {
		if (_businessDomainId == null) {
			return StringPool.BLANK;
		}
		else {
			return _businessDomainId;
		}
	}

	@Override
	public void setBusinessDomainId(String businessDomainId) {
		_columnBitmask |= BUSINESSDOMAINID_COLUMN_BITMASK;

		if (_originalBusinessDomainId == null) {
			_originalBusinessDomainId = _businessDomainId;
		}

		_businessDomainId = businessDomainId;
	}

	public String getOriginalBusinessDomainId() {
		return GetterUtil.getString(_originalBusinessDomainId);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public BusinessDomain toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (BusinessDomain)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BusinessDomainImpl businessDomainImpl = new BusinessDomainImpl();

		businessDomainImpl.setBusinessId(getBusinessId());
		businessDomainImpl.setBusinessDomainId(getBusinessDomainId());

		businessDomainImpl.resetOriginalValues();

		return businessDomainImpl;
	}

	@Override
	public int compareTo(BusinessDomain businessDomain) {
		BusinessDomainPK primaryKey = businessDomain.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof BusinessDomain)) {
			return false;
		}

		BusinessDomain businessDomain = (BusinessDomain)obj;

		BusinessDomainPK primaryKey = businessDomain.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
		BusinessDomainModelImpl businessDomainModelImpl = this;

		businessDomainModelImpl._originalBusinessId = businessDomainModelImpl._businessId;

		businessDomainModelImpl._setOriginalBusinessId = false;

		businessDomainModelImpl._originalBusinessDomainId = businessDomainModelImpl._businessDomainId;

		businessDomainModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<BusinessDomain> toCacheModel() {
		BusinessDomainCacheModel businessDomainCacheModel = new BusinessDomainCacheModel();

		businessDomainCacheModel.businessId = getBusinessId();

		businessDomainCacheModel.businessDomainId = getBusinessDomainId();

		String businessDomainId = businessDomainCacheModel.businessDomainId;

		if ((businessDomainId != null) && (businessDomainId.length() == 0)) {
			businessDomainCacheModel.businessDomainId = null;
		}

		return businessDomainCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{businessId=");
		sb.append(getBusinessId());
		sb.append(", businessDomainId=");
		sb.append(getBusinessDomainId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("org.opencps.accountmgt.model.BusinessDomain");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>businessId</column-name><column-value><![CDATA[");
		sb.append(getBusinessId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>businessDomainId</column-name><column-value><![CDATA[");
		sb.append(getBusinessDomainId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = BusinessDomain.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			BusinessDomain.class
		};
	private long _businessId;
	private long _originalBusinessId;
	private boolean _setOriginalBusinessId;
	private String _businessDomainId;
	private String _originalBusinessDomainId;
	private long _columnBitmask;
	private BusinessDomain _escapedModel;
}